---
- name: Debug import_crds
  debug:
    var: import_crds

- name: Debug import_ros
  debug:
    var: import_ros
    
- name: Apply CRDs to the managed cluster
  kubernetes.core.k8s:
    host: "{{ rhacmreg_mc_api }}"
    api_key: "{{ rhacmreg_mc_apikey }}"
    ca_cert: "{{ rhacmreg_mc_cacert }}"
    state: present
    definition: "{{ import_crds | b64decode }}"

- name: Apply ROs to the managed cluster
  kubernetes.core.k8s:
    host: "{{ rhacmreg_mc_api }}"
    api_key: "{{ rhacmreg_mc_apikey }}"
    ca_cert: "{{ rhacmreg_mc_cacert }}"
    state: present
    definition: "{{ import_ros | b64decode }}"