---
- name: Debug import_crds
  debug:
    var: import_crds

- name: Debug import_ros
  debug:
    var: import_ros
    
- name: Apply CRDs to the managed cluster
  kubernetes.core.k8s:
    host: "{{ rhacmreg_mc_api }}"
    username: "{{ rhacmreg_mc_username }}"
    password: "{{ rhacmreg_mc_password }}"
    validate_certs: "{{ rhacmreg_mc_validate }}"
    ca_cert: "{{ rhacmreg_mc_cacert }}"
    state: present
    definition: "{{ import_crds | b64decode }}"
  register: crds_import_results

- name: Apply ROs to the managed cluster
  kubernetes.core.k8s:
    host: "{{ rhacmreg_mc_api }}"
    username: "{{ rhacmreg_mc_username }}"
    password: "{{ rhacmreg_mc_password }}"
    validate_certs: "{{ rhacmreg_mc_validate }}"
    ca_cert: "{{ rhacmreg_mc_cacert }}"
    state: present
    definition: "{{ import_ros | b64decode }}"
  register: ros_import_results
